name: security_2025_mobile_v3
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+7

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cupertino_stepper: ^0.2.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.10.1
  firebase_core_platform_interface: ^5.4.0
  firebase_messaging: ^15.2.1
  # flutter_datetime_picker: ^1.5.1
  flutter_downloader: ^1.7.1
  flutter_facebook_auth: ^7.1.1
  # flutter_facebook_login: ^3.0.0
  flutter_line_sdk: ^2.5.0
  # flutter_pdfview: ^1.2.a1
  flutter_picker: ^2.0.2
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.17
  # geocoder: ^0.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.0.0
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.4.0
  # loading: ^1.0.2
  location: ^7.0.1
  numeric_keyboard: ^1.1.0
  path_provider: ^2.0.8
  photo_view: ^0.15.0
  pull_to_refresh: ^2.0.0
  # share: ^2.0.4
  share_plus: ^7.2.2
  sign_in_with_apple: ^6.1.4
  sliding_up_panel: ^2.0.0+1
  # splashscreen: ^1.3.5
  tab_indicator_styler: ^2.0.0
  table_calendar: ^3.0.3
  # toast: ^0.1.5
  url_launcher: ^6.1.5
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.4
  flutter_native_splash: ^2.3.10
  flutter_spinkit: ^5.2.0
  flutter_datetime_picker_plus: ^2.0.0
  file_picker: ^5.3.2
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  pinput: ^5.0.1
  webview_flutter: ^4.10.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon-security3.png"
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/background/
    - assets/logo/icons/
    - assets/images/
    - assets/logo/socials/
    - assets/logo/icons/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
        - asset: assets/fonts/Kanit-Medium.ttf
        - asset: assets/fonts/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit-SemiBold.ttf

    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
        - asset: assets/fonts/Sarabun-Light.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Thin.ttf

    - family: Mitr
      fonts:
        - asset: assets/fonts/Mitr-Bold.ttf
        - asset: assets/fonts/Mitr-Regular.ttf


  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
